# Generated by Django 6.0.4 on 2026-05-05 06:45

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0001_initial'),
        ('devices', '0005_device_room'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direction', models.CharField(choices=[('in', 'KIRDI'), ('out', 'CHIQDI')], max_length=3, verbose_name='Yo\'nalish')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Vaqt')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='devices.device', verbose_name='Qurilma')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='device_logs', to='user_management.userprofile', verbose_name='Foydalanuvchi')),
            ],
            options={
                'verbose_name': 'Qurilma logi',
                'verbose_name_plural': 'Qurilma loglari',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.AddIndex(
            model_name='devicelog',
            index=models.Index(fields=['-timestamp'], name='devices_devicelog_timestamp_idx'),
        ),
        migrations.AddIndex(
            model_name='devicelog',
            index=models.Index(fields=['user', '-timestamp'], name='devices_devicelog_user_timestamp_idx'),
        ),
        migrations.AddIndex(
            model_name='devicelog',
            index=models.Index(fields=['device', '-timestamp'], name='devices_devicelog_device_timestamp_idx'),
        ),
    ]
