# Generated by Django 6.0.4 on 2026-05-05 04:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0002_devicelog'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='devicelog',
            new_name='devices_dev_timesta_79151c_idx',
            old_name='devices_devicelog_timestamp_idx',
        ),
        migrations.RenameIndex(
            model_name='devicelog',
            new_name='devices_dev_user_id_722b03_idx',
            old_name='devices_devicelog_user_timestamp_idx',
        ),
        migrations.RenameIndex(
            model_name='devicelog',
            new_name='devices_dev_device__b10ac7_idx',
            old_name='devices_devicelog_device_timestamp_idx',
        ),
    ]
