# Generated by Django 6.0.4 on 2026-04-29 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0003_alter_device_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
