# Generated by Django 6.0

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0004_alter_device_name'),
        ('rooms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='room',
            field=models.OneToOneField(
                blank=True,
                help_text='Faqat «Xona» turidagi qurilmalar uchun. Har bir xonada bitta qurilma.',
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name='attendance_device',
                to='rooms.room',
                verbose_name='Xona',
            ),
        ),
    ]
