# Generated by Django 6.0.4 on 2026-05-02 06:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0001_initial'),
        ('user_management', '0006_alter_userprofile_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupStudent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faol')),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_memberships', to='groups.group', verbose_name='Guruh')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_memberships', to='user_management.userprofile', verbose_name='Talaba')),
            ],
            options={
                'verbose_name': 'Guruh talabasi',
                'verbose_name_plural': 'Guruh talabalari',
                'ordering': ['group__group_name', 'student__last_name', 'student__first_name'],
                'constraints': [models.UniqueConstraint(fields=('group', 'student'), name='unique_group_student_membership')],
            },
        ),
    ]
