# Generated by Django 6.0.4 on 2026-05-02 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0002_groupstudent'),
        ('user_management', '0006_alter_userprofile_role'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='groupstudent',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('student',), name='unique_active_group_per_student'),
        ),
    ]
