# Generated by Django 6.0

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('groups', '0003_groupstudent_unique_active_group_per_student'),
        ('rooms', '0001_initial'),
        ('subjects', '0002_subject_is_active'),
        ('user_management', '0006_alter_userprofile_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupSubject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faol')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                (
                    'group',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='group_subjects',
                        to='groups.group',
                        verbose_name='Guruh',
                    ),
                ),
                (
                    'subject',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name='group_offerings',
                        to='subjects.subject',
                        verbose_name='Fan',
                    ),
                ),
                (
                    'teacher',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name='teaching_assignments',
                        to='user_management.userprofile',
                        verbose_name="O'qituvchi",
                    ),
                ),
            ],
            options={
                'verbose_name': 'Guruh fani',
                'verbose_name_plural': 'Guruh fanlari',
                'ordering': ['group__group_name', 'subject__subject_name'],
            },
        ),
        migrations.CreateModel(
            name='LessonSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weekday', models.PositiveSmallIntegerField(choices=[(1, 'Dushanba'), (2, 'Seshanba'), (3, 'Chorshanba'), (4, 'Payshanba'), (5, 'Juma'), (6, 'Shanba'), (7, 'Yakshanba')], verbose_name='Hafta kuni')),
                ('start_time', models.TimeField(verbose_name='Boshlanish')),
                ('end_time', models.TimeField(verbose_name='Tugash')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faol')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                (
                    'group_subject',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='lesson_slots',
                        to='schedule.groupsubject',
                        verbose_name='Guruh fani',
                    ),
                ),
                (
                    'room',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name='lesson_slots',
                        to='rooms.room',
                        verbose_name='Xona',
                    ),
                ),
            ],
            options={
                'verbose_name': 'Dars sloti',
                'verbose_name_plural': 'Dars slotlari',
                'ordering': ['weekday', 'start_time', 'group_subject__group__group_name'],
            },
        ),
        migrations.AddConstraint(
            model_name='groupsubject',
            constraint=models.UniqueConstraint(fields=('group', 'subject'), name='unique_group_subject_offering'),
        ),
    ]
