# Generated by Django 6.0.4 on 2026-05-04 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lessonslot',
            options={'ordering': ['weekday', 'lesson_number', 'group_subject__group__group_name'], 'verbose_name': 'Dars sloti', 'verbose_name_plural': 'Dars slotlari'},
        ),
        migrations.AddField(
            model_name='lessonslot',
            name='lesson_number',
            field=models.PositiveSmallIntegerField(choices=[(1, '1-para (08:30-09:50)'), (2, '2-para (10:00-11:20)'), (3, '3-para (11:30-12:50)'), (4, '4-para (13:30-15:50)'), (5, '5-para (16:00-17:20)')], default=1, verbose_name='Para'),
        ),
        migrations.AlterField(
            model_name='lessonslot',
            name='end_time',
            field=models.TimeField(editable=False, verbose_name='Tugash'),
        ),
        migrations.AlterField(
            model_name='lessonslot',
            name='start_time',
            field=models.TimeField(editable=False, verbose_name='Boshlanish'),
        ),
    ]
