# Generated by Django 6.0.4 on 2026-05-04 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0002_alter_lessonslot_options_lessonslot_lesson_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lessonslot',
            name='weekday',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Dushanba'), (2, 'Seshanba'), (3, 'Chorshanba'), (4, 'Payshanba'), (5, 'Juma'), (6, 'Shanba')], verbose_name='Hafta kuni'),
        ),
    ]
