# Generated by Django 6.0.4 on 2026-04-30 03:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hodimlar', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Employee',
        ),
    ]
