# Generated by Django 6.0.4 on 2026-05-01 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0003_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userprofile',
            options={'ordering': ['last_name', 'first_name'], 'verbose_name': 'Foydalanuvchi', 'verbose_name_plural': 'Foydalanuvchilar'},
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='position',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='user',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='ais_id',
            field=models.CharField(default='', max_length=100, unique=True, verbose_name='AIS ID'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='face_id',
            field=models.CharField(default='', max_length=100, unique=True, verbose_name='Face ID'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('teacher', "O'qituvchi"), ('student', 'Talaba'), ('staff', 'Xodim')], default='student', max_length=20, verbose_name='Lavozim'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
