# Generated by Django 6.0.4 on 2026-05-01 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0005_userprofile_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('student', 'Talaba'), ('teacher', "O'qituvchi"), ('staff', 'Xodim')], default='student', max_length=20, verbose_name='Lavozim'),
        ),
    ]
